# Introduction to Julia

In [1]:
1 + 2

3

In [2]:
1.2 + 2

3.2

In [3]:
23/5

4.6

In [4]:
5^2

25

In [5]:
3//4  # rationals

3//4

In [6]:
3//4 + 5//8  # rationals

11//8

In [7]:
BigInt(23)^523

15263644314370186088927158246093742290149550661978363178576873509024577612651099949113075299588485277118597071400884387252233130970923430953047394509736393827389789614315462805196788292335044240070226596032045907951794740009010812659469824794635407880186178589469066563009977170965506122264615544713932438651506970606675818631131424867489169161799258057246459294610545232597972770291900208702668866581076702155727578360510255564530490055647366951961018099239472001069055289397268896217585252184061447175104936807612544466676366739280843328126457749496390288328247856202468336860117443975116258779898622759889504555662621523778503245913166695398227016177513174953868894552626014243920282555704603062402224951370567

In [8]:
2 + 3im

2 + 3im

In [9]:
conj(2 + 3im)

2 - 3im

In [10]:
(1 + 23im) * (5 + 42im)

-961 + 157im

In [11]:
"a string"

"a string"

In [12]:
'a char'

LoadError: syntax: invalid character literal

In [13]:
'a'  # char

'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)

In [14]:
array = [1, 2, 3, 4]

4-element Array{Int64,1}:
 1
 2
 3
 4

In [15]:
array[1]  # 1-based indexing

1

In [16]:
[[1, 2, 3], [4, 5, 6]]

2-element Array{Array{Int64,1},1}:
 [1, 2, 3]
 [4, 5, 6]

In [17]:
[[1 2 3], [4 5 6]]

2-element Array{Array{Int64,2},1}:
 [1 2 3]
 [4 5 6]

In [18]:
[[1 2 3]; [4 5 6]]

2×3 Array{Int64,2}:
 1  2  3
 4  5  6

In [19]:
[[1, 2, 3]; [4, 5, 6]]

6-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6

### Julia is column-major! (Just like Fortran)

In [20]:
M = [[1 2 3]; [4 5 6]]

2×3 Array{Int64,2}:
 1  2  3
 4  5  6

In [21]:
M[1,:]  # select all elements of the first column

3-element Array{Int64,1}:
 1
 2
 3

In [22]:
M[:,1]  # the first column of the all rows

2-element Array{Int64,1}:
 1
 4

In [23]:
M * 2

2×3 Array{Int64,2}:
 2   4   6
 8  10  12

In [24]:
M

2×3 Array{Int64,2}:
 1  2  3
 4  5  6

In [25]:
M * [1, 2, 3]  # matrix multiplication

2-element Array{Int64,1}:
 14
 32

In [26]:
size(M)

(2, 3)

In [27]:
size([1, 2])

(2,)

In [28]:
M .* [1, 2]  # similar broadcasting rules as in numpy

2×3 Array{Int64,2}:
 1   2   3
 8  10  12

In [29]:
M

2×3 Array{Int64,2}:
 1  2  3
 4  5  6

In [30]:
M \ [23, 5]

3-element Array{Float64,1}:
 -19.5
  -2.0
  15.5

### backup

In [31]:
sum(M[1,:] .* [-19, -2, 15.5])

23.5

In [32]:
sum(M[2,:] .* [-19, -2, 15.5])

7.0

In [33]:
M = [[1 2]; [3 4]]

2×2 Array{Int64,2}:
 1  2
 3  4

In [34]:
M \ [23, 5]

2-element Array{Float64,1}:
 -41.0
  32.0

In [35]:
sum(M[1,:] .* [-41, 32])

23

In [36]:
sum(M[2,:] .* [-41, 32])

5

### proceed

In [37]:
diagm([9, 8, 7])

3×3 Array{Int64,2}:
 9  0  0
 0  8  0
 0  0  7

In [38]:
M = [[1 2 3]; [4 5 6]]

2×3 Array{Int64,2}:
 1  2  3
 4  5  6

In [39]:
M' * M  # transpose

3×3 Array{Int64,2}:
 17  22  27
 22  29  36
 27  36  45

### array creation helper functions

In [40]:
eye(4)

4×4 Array{Float64,2}:
 1.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0
 0.0  0.0  1.0  0.0
 0.0  0.0  0.0  1.0

In [41]:
zeros(3)

3-element Array{Float64,1}:
 0.0
 0.0
 0.0

In [42]:
zeros(3, 2)

3×2 Array{Float64,2}:
 0.0  0.0
 0.0  0.0
 0.0  0.0

In [43]:
rand(2, 5)

2×5 Array{Float64,2}:
 0.417871   0.973584  0.74141   0.393815  0.0987592
 0.0247374  0.773067  0.883871  0.236263  0.728932 

In [44]:
rand(Bool, 4)

4-element Array{Bool,1}:
  true
 false
 false
  true

In [45]:
rand(UInt32, 3, 5)

3×5 Array{UInt32,2}:
 0xda109f08  0x85dd70d2  0x8c083b80  0xb84f9c54  0x33085b1e
 0x6ef0e7e4  0xf1f9f420  0x6a4bcf16  0x49e9109b  0xc391d0e2
 0xdb29a803  0x967230a3  0xd6a4fade  0xafa6c7ff  0xe23bf387

## Type Inference

In [46]:
[1, 2, 3]

3-element Array{Int64,1}:
 1
 2
 3

In [47]:
[42.0, 2.3, 23.5]

3-element Array{Float64,1}:
 42.0
  2.3
 23.5

In [48]:
[1, 2, 3.0]

3-element Array{Float64,1}:
 1.0
 2.0
 3.0

In [49]:
[1, 2, 'a']

3-element Array{Any,1}:
 1   
 2   
  'a'

In [50]:
Array{Float32}([1, 2, 3])

3-element Array{Float32,1}:
 1.0
 2.0
 3.0

In [51]:
d = Dict("foo" => 23, "bar" => 42)

Dict{String,Int64} with 2 entries:
  "bar" => 42
  "foo" => 23

In [52]:
for (key, value) in d
    println("key: $key, value: $value")
end

key: bar, value: 42
key: foo, value: 23


### tuples

In [53]:
(1, 2, 3)

(1, 2, 3)

In [54]:
typeof((1, 2, 3))

Tuple{Int64,Int64,Int64}

In [55]:
typeof((1, 2.0, 'a'))

Tuple{Int64,Float64,Char}

In [56]:
"abc" * "def"

"abcdef"

### list comprehension

In [57]:
[x*23 for x ∈ 1:5]

5-element Array{Int64,1}:
  23
  46
  69
  92
 115

## Functions

In [58]:
f(x) = 2x + 1

f (generic function with 1 method)

In [59]:
f(23)

47

In [60]:
function add(a, b)
    a + b
end

add (generic function with 1 method)

In [61]:
methods(add)

# 1 method for generic function "add":
add(a, b) in Main at In[60]:2

In [62]:
add(1, 2)

3

In [63]:
@code_llvm add(1, 2)


define i64 @julia_add_63683(i64, i64) #0 !dbg !5 {
top:
  %2 = add i64 %1, %0
  ret i64 %2
}


In [64]:
@code_llvm add(1.0, 2)


define double @julia_add_63707(double, i64) #0 !dbg !5 {
top:
  %2 = sitofp i64 %1 to double
  %3 = fadd double %2, %0
  ret double %3
}


In [65]:
@code_warntype add(1.0, 2)

Variables:
  #self# <optimized out>
  a::Float64
  b::Int64

Body:
  begin 
      return (Base.add_float)(a::Float64, (Base.sitofp)(Float64, b::Int64)::Float64)::Float64
  end::Float64


In [66]:
@code_native add(1.0, 2)

	.section	__TEXT,__text,regular,pure_instructions
Filename: In[60]
	pushl	%ebp
	decl	%eax
	movl	%esp, %ebp
Source line: 2
	xorps	%xmm1, %xmm1
	repne
	decl	%eax
	cvtpi2ps	%mm7, %xmm1
	addsd	%xmm1, %xmm0
	popl	%ebp
	retl
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop


In [67]:
add(1.0, 2.0)

3.0

In [68]:
function add(a::Int, b::Int)
    return 23
end

add (generic function with 2 methods)

In [69]:
methods(add)

# 2 methods for generic function "add":
add(a::Int64, b::Int64) in Main at In[68]:2
add(a, b) in Main at In[60]:2

In [70]:
add(3, 4)

23

In [71]:
add(3.0, 4.0)

7.0

In [72]:
add("abc", "def")

LoadError: MethodError: no method matching +(::String, ::String)
Closest candidates are:
  +(::Any, ::Any, ::Any, ::Any...) at operators.jl:424

In [73]:
function add(s1::T, s2::T) where {T<:AbstractString}
    return s1 * s2
end

add (generic function with 3 methods)

In [74]:
add("abc", "def")

"abcdef"

In [75]:
function add(s1::T, s2::T) where {T<:AbstractString}
    println("Calling with type $T")
    return s1 * s2
end

add (generic function with 3 methods)

In [76]:
add("abc", "def")

Calling with type String


"abcdef"

### types

In [77]:
typeof(1)

Int64

In [78]:
typeof(Int64)

DataType

In [79]:
typeof(DataType)

DataType

In [80]:
supertype(Int64)

Signed

In [81]:
supertype(Signed)

Integer

In [82]:
supertype(Integer)

Real

In [83]:
supertype(Real)

Number

In [84]:
supertype(Number)

Any

In [85]:
subtypes(Number)

2-element Array{Union{DataType, UnionAll},1}:
 Complex
 Real   

In [86]:
subtypes(Real)

4-element Array{Union{DataType, UnionAll},1}:
 AbstractFloat
 Integer      
 Irrational   
 Rational     

In [87]:
subtypes(AbstractFloat)

4-element Array{Union{DataType, UnionAll},1}:
 BigFloat
 Float16 
 Float32 
 Float64 

In [88]:
subtypes(Float64)

0-element Array{Union{DataType, UnionAll},1}

In [89]:
isleaftype(Float64)  # you can only instantiate concrete types!

true

In [90]:
Number(23)

23

In [91]:
@which Number(23)

(::Type{T})(arg) where T in Base at sysimg.jl:77

In [92]:
# @edit(Number(23))

In [93]:
# @edit(1+2)

In [94]:
function mysqrt__(x::T) where {T<:AbstractFloat}
    return sqrt(x)
end

mysqrt__ (generic function with 1 method)

In [95]:
mysqrt__(3)

LoadError: MethodError: no method matching mysqrt__(::Int64)
Closest candidates are:
  mysqrt__(::T<:AbstractFloat) where T<:AbstractFloat at In[94]:2

In [96]:
struct YourInt <: Real
    x::Int64
end

In [97]:
function add(a::YourInt, b::YourInt)
    return YourInt(a.x + b.x)
end

add (generic function with 4 methods)

In [98]:
add(YourInt(23), YourInt(5))

YourInt(28)

In [99]:
using BenchmarkTools

In [100]:
@benchmark add(YourInt(23), YourInt(5))

BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     1.592 ns (0.00% GC)
  median time:      1.598 ns (0.00% GC)
  mean time:        1.839 ns (0.00% GC)
  maximum time:     22.362 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1000

In [101]:
@benchmark 23 + 5

BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     1.597 ns (0.00% GC)
  median time:      1.601 ns (0.00% GC)
  mean time:        2.155 ns (0.00% GC)
  maximum time:     42.373 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1000

### one more thing

In [102]:
using PyCall

In [103]:
@pyimport matplotlib.pyplot as plt

In [104]:
plt.plot

PyObject <function plot at 0x1204b5268>

In [105]:
plt.plot(collect(1:10), rand(10))

1-element Array{PyCall.PyObject,1}:
 PyObject <matplotlib.lines.Line2D object at 0x12361ef28>

In [106]:
@pyimport numpy as np

In [107]:
np.random[:random](10)

10-element Array{Float64,1}:
 0.265281
 0.573849
 0.751795
 0.995779
 0.808557
 0.596388
 0.282448
 0.840536
 0.669729
 0.849852

In [108]:
a = rand(500, 500)

500×500 Array{Float64,2}:
 0.484564   0.0185085  0.916284   …  0.00322092  0.0871586  0.17601   
 0.440093   0.860415   0.504961      0.429534    0.0792908  0.33112   
 0.357106   0.310498   0.0516811     0.353311    0.238598   0.748007  
 0.205235   0.137847   0.0196097     0.390106    0.393783   0.100668  
 0.324348   0.690132   0.858016      0.141402    0.455206   0.502559  
 0.780727   0.0153615  0.821111   …  0.0523588   0.490309   0.234587  
 0.153104   0.922491   0.0427586     0.532023    0.714558   0.0751153 
 0.561716   0.934665   0.936695      0.633257    0.526354   0.2362    
 0.478128   0.170044   0.54991       0.323357    0.186217   0.746546  
 0.637628   0.29482    0.337347      0.0476663   0.99168    0.13621   
 0.612164   0.856022   0.866328   …  0.582754    0.028089   0.986188  
 0.0119124  0.464205   0.690936      0.258005    0.295937   0.0371068 
 0.289591   0.0763635  0.265836      0.0422629   0.476436   0.0589847 
 ⋮                                ⋱                

In [109]:
using BenchmarkTools

In [110]:
@benchmark np.sin(a)

BenchmarkTools.Trial: 
  memory estimate:  1.91 MiB
  allocs estimate:  95
  --------------
  minimum time:     3.316 ms (0.00% GC)
  median time:      3.991 ms (0.00% GC)
  mean time:        5.011 ms (4.20% GC)
  maximum time:     16.581 ms (23.26% GC)
  --------------
  samples:          996
  evals/sample:     1

In [111]:
@benchmark sin.(a)

BenchmarkTools.Trial: 
  memory estimate:  1.91 MiB
  allocs estimate:  26
  --------------
  minimum time:     2.201 ms (0.00% GC)
  median time:      2.501 ms (0.00% GC)
  mean time:        2.754 ms (8.06% GC)
  maximum time:     9.115 ms (48.01% GC)
  --------------
  samples:          1806
  evals/sample:     1

### 30% faster, less alocations... and this is just a simple function on a standard datatype

### of course Julia wants to eliminate the two language problem, but why not ;)